---
# tasks file for deployment

  - name: Print OS version
    debug: var=ansible_os_family

  - name: include vars
    include_vars:
      file: /home/ansible/roles/provisioning/vars/main.yaml


  - block: #=========Block for DEBIAN============

      - name: Copy proj to folder
#        include_vars:
#          file: /home/ansible/roles/provisioning/vars/main.yaml
#          name: stuff
        copy:
          src: v_1.jar
          dest: /home/{{ username }}/for_javabuild/v_1.jar
          owner: "{{ username }}"
          group: "{{ username }}"
          mode: '0644'

      - name: Run jar-file
        shell: "nohup java -jar /home/{{ username }}/for_javabuild/v_1.jar --server.port={{ port }} &"
        register: status1

      - debug:
          var: status1


      - name: Check util status
        shell: "ps -aux | grep java"
        register: status1

      - debug:
          var: status1.stdout_lines

    when: ansible_os_family == "Debian"
